export const sectionIds = [
  "project_overview",
  "initial_situation_problem",
  "goals",
  "core_idea_solution",
  "target_group",
  "vision_target_state",
  "scope_features",
  "requirements",
  "frontend_backend_features",
  "technical_concept",
  "design_ux_concept",
  "content_data_concept",
  "sales_marketing_concept",
  "market_potential",
  "monetization_business_model",
  "revenue_scenarios",
  "cost_structure",
  "profitability",
  "billing_invoice_model",
  "roadmap_phases",
  "milestones",
  "current_status",
  "risks_challenges",
  "scaling_potential",
  "communication_coordination",
  "next_steps",
  "management_summary",
  "appendix",
] as const

export type SectionId = (typeof sectionIds)[number]
